### ISSUE TITLE
Web3: If a user signs up and doesn't create a wallet after 2 days - send him a "Good time to go to your wallet"

### ISSUE THREAD

**Issue by LiavGut** [GoodDollar/GoodLearning#8]
Web3: If a user signs up and doesn't create a wallet after 2 days - send him a "Good time to go to your wallet" email

* Only if and when the user been verified by his inviter on web3.

**Comment by Talbatz** [comment]
Very good idea!

**Comment by LiavGut** [comment]
@amitorama Please write the text for this email.

**Comment by amitorama** [comment]
https://docs.google.com/document/d/1B0V4Pumzp0LC7E-S7Om3OfenLxyXQq7cvn2aymn5aAU/edit#
